exports.data = {
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },

"features": [
{ "type": "Feature", "properties": { "Name": "Chats de Ruelles", "description": "<img src=\"https:\/\/lh3.googleusercontent.com\/0rUX7EDr4BdDwtfUSmAbC2aao1dBAroJTgEVrFRg0VzwnLJ8KfjHB4qIWiQBp6fc7eCb3i_HGWujB0H2y50VWbrFUSYFcExD_-hTd7vMc8iG_KtLcIZoXfnXMMjzqXY\" height=\"200\" width=\"auto\" \/><br><br>", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": -1, "visibility": -1, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ -73.6123091, 45.5210335, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Chats de Ruelles", "description": "<img src=\"https:\/\/lh5.googleusercontent.com\/KPVISD-9GBh23MULmu1Ir816puUzUJL8uI2b07kilvXLdMsqRCAsFLK8qJxGz5A4OM0O90s6xWYxAsQjfKB7sTMe_kIjGenodjncIuq3-YR-PF1gTpOc_1f-YASfcz4O\" height=\"200\" width=\"auto\" \/><br><br>", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": -1, "visibility": -1, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ -73.6337721, 45.5057605, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Chats de Ruelles", "description": "<img src=\"https:\/\/lh5.googleusercontent.com\/PK6UtTTWn0aqA-kV-5QoX_L2vTWJpYrwQLpdOFkZloZ_gZ_nlyK4iESDmnQPPt7l91D8KNkWpDDu20lcl4qyoE8TD0UcctCCvy14sFghA8VQa0d7TAxxlNbsR8buYKg\" height=\"200\" width=\"auto\" \/><br><br>", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": -1, "visibility": -1, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ -73.5141027, 45.5978325, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Chats de Ruelles", "description": "<img src=\"https:\/\/lh4.googleusercontent.com\/_s6TX1jWPtWl3SvGZ-lQa10vbajAi8uRhiunKfEoe9k_yccyk0rcP95zijr5b3xZfwoGW0muqnsd6pAshb65AlQ8QGllCWTpxcz588xQ76TY_25_w7TS-PivXK9hpYgp\" height=\"200\" width=\"auto\" \/><br><br>", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": -1, "visibility": -1, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ -73.5833788, 45.6030495, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Chats de Ruelles", "description": "<img src=\"https:\/\/lh5.googleusercontent.com\/BMHLRQMv3mAUtLT9iCR43vPvHWyRuMCCD1FcFKiT9_O4x4Jmsf1rOXESTCyVZthdb60-A_om39wTnjCT5No3ZPrmw62p7zDWIYZm1DrGqhkEnxQy1PdFmk1xzKIqJxjNiA\" height=\"200\" width=\"auto\" \/><br><br>", "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1, "extrude": -1, "visibility": -1, "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ -73.5934317, 45.5866836, 0.0 ] } }
]
}
